# Generated by Django 3.0.5 on 2020-04-30 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200429_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 18, 49, 55, 246908, tzinfo=utc)),
        ),
    ]
