# Generated by Django 3.0.5 on 2020-05-01 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200501_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 8, 16, 49, 378161, tzinfo=utc)),
        ),
    ]
