# Generated by Django 3.0.5 on 2020-05-03 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_auto_20200503_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_downvoted_users',
            field=models.ManyToManyField(related_name='comment_downvoted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_upvoted_users',
            field=models.ManyToManyField(related_name='comment_upvoted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
