# Generated by Django 3.0.5 on 2020-05-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200503_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='downvote_count',
            new_name='comment_downvote_count',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='upvote_count',
            new_name='comment_upvote_count',
        ),
    ]
