# Generated by Django 3.0.5 on 2020-05-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200503_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnails'),
        ),
    ]
